<div data-bind="scope: 'koexample'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "koexample": {
                            "component": "Webjump_KnockoutStudy/js/koexample",
                            "template" : "Webjump_KnockoutStudy/example"
                        }
                    }
                }
            }
        }
</script>
